services:

  agenda_api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - AUTH_MICROSERVICE_HOST=agenda_auth
      - AUTH_MICROSERVICE_PORT=3001
      - JOBRUNNER_MICROSERVICE_HOST=agenda_jobrunner
      - JOBRUNNER_MICROSERVICE_HOST_MICROSERVICE_PORT=3004
    depends_on:
      - postgres

  agenda_auth:
    build:
      context: .
      dockerfile: Dockerfile
      target: auth
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - AUTH_MICROSERVICE_HOST=agenda_auth
      - AUTH_MICROSERVICE_PORT=3001
      - MAIL_HOST=maildev
      - FRONT_URL=http://localhost:5173
    depends_on:
      - postgres

  agenda_jobrunner:
    build:
      context: .
      dockerfile: Dockerfile
      target: jobrunner
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - JOBRUNNER_MICROSERVICE_HOST=agenda_jobrunner
      - JOBRUNNER_MICROSERVICE_PORT=3004
    depends_on:
      - postgres

  agenda_ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: ui
    ports:
      - "5173:5173"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./test_init.sql:/docker-entrypoint-initdb.d/test_init.sql

  maildev:
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"

  redis:
    image: redis
