services:
  agenda_api:
    build: ./apps/api

  agenda_ui:
    build: ./apps/ui
    ports:
      - "8080:80"
    depends_on:
      - agenda_api

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432

  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8082:8080

  maildev:
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
      - "25:25"

  redis:
    image: redis
    ports:
      - 6379:6379

  redis_insight:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - redis_insight_volume:/data

volumes:
  redis_insight_volume:

