// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               v5.28.3
// source: notification.proto

/* eslint-disable */
export interface empty {}

export interface text {
  text: string;
}

export interface notificationList {
  notifications: notification[];
}

export interface notificationId {
  id: string;
}

export interface notification {
  text: string;
}

export interface addNotification {
  text: string;
  delay: number;
}

export interface userId {
  id: string;
}

function createBaseempty(): empty {
  return {};
}
